### PR TITLE
Add ability to create transparent slippy images for overlays.

### PR DESCRIPTION
**Pull request by antihax**
Allows users to create images without islands, background, etc for slippy overlays.

### CODE REVIEW

**Comment by antihax** [comment]
Added cleaner grid information option for slippy maps.
https://puu.sh/DaS7A/04f5ada410.png
See: https://antihax.github.io/ for example use.

**Comment by MagicTrevor** [comment]
I tried yours @antihax but some of the tiles come out entirely black.

**Comment by antihax** [comment]
> I tried yours @antihax but some of the tiles come out entirely black.

It should generate images based on what is currently seen on the screen with the exception that it will be transparent if selected.

Which ones came out black and what were the options you had selected on the application? I will see if i can replicate tonight.

**Comment by MagicTrevor** [comment]
I had islands enabled, water background disabled and alpha enabled. The first few zoom levels were fine but by 4-6 a quarter of the tiles were black instead of normal

**Comment by smooreace** [comment]
The Alpha layer is what did it Im betting

**Comment by MagicTrevor** [comment]
Am I not supposed to select that or you saying there could be a bug there?

**Comment by smooreace** [comment]
It's just a guess.  I'm not sure how any of that is implemented. I THINK
the alpha layer is the transparency. And I'm guessing that it's not being
applied properly. Unchecking it will give a solid image, but you can pretty
easily remove that all white background in photoshop or gimp and make it
transparent again. Ive been doing all of mine manually

**Comment by antihax** [comment]
It should allow transparency through an alpha channel because that was the intent. I.e.

Export a base set of images which includes the background (usually the background with islands) then export additional sets with no background and just specific elements, such as grid, server information, island names, discoveries. These additional sets can then be applied as layers in leaflet.

**Comment by smooreace** [comment]
The damn slippy export is not working properly though. Not your version
specifically. Even in the official version its broke. So Ive just about
given up on a live map

**Comment by MagicTrevor** [comment]
Official works unless you want a transparent background and just the islands, then you get a blue background color.

**Comment by smooreace** [comment]
It doesnt with a custom water tile because there is no autoscale file for
it. And god knows WTF that is

**Comment by MagicTrevor** [comment]
@antihax were you able to look into it?

**Comment by antihax** [comment]
Yes, i replicated and this appears to be not an issue. The black thumbnails are fully transparent images.

https://puu.sh/DnvzC/04eb6f2fae.png

**Comment by antihax** [comment]
@GrapeshotGames this PR should be good to go if you have time to review.

**Comment by antihax** [comment]
Drifted too far from master.

**Pull request closed without merging**
